---
- hosts: tomcat_server
  become: true
  vars:
  - warName: springwebapp.war
  - warRemotePath: /usr/share/tomcat/webapps

  tasks:
  - name: Find the previous release
    shell: ls -t | head -2 | tail -1
    args:
      chdir: "{{ warRemotePath }}"
    register: ls_output

  - debug: var=ls_output.stdout_lines[0]

  - name: Replace the war with previous release
    shell: 'cp {{ ls_output.stdout_lines[0] }} {{ warName }}'
    args:
      chdir: "{{ warRemotePath }}"

