---
- hosts: tomcat_server
  become: true
  vars:
  - warName: springwebapp.war
  - warLocalPath: /root/.jenkins/workspace/Demo/target
  - warRemotePath: /usr/share/tomcat/webapps

  tasks:
  - name: Copying war file to Remote Server
    copy:
      src: "{{ warLocalPath }}/{{ warName }}"
      dest: "{{ warRemotePath}}/{{ warName }}"
      owner: tomcat
      group: tomcat
      mode: '0755'
      backup: yes

  - name: Restart tomcat
    service:
      name: tomcat
      state: restarted
#testing1
